Description: >

  This template deploys a VPC, with public and private subnets. 
  It deploys an Internet Gateway, with a default route on the public subnets.
  It deploys a NAT Gateway, and default route for them in the private subnets.
  It then deploys a ECS cluster. Finally, it creates task definition in cluster

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-zuram.s3.us-east-2.amazonaws.com/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.10.0.0/16
        PrivateSubnetCIDR: 10.10.10.0/24
        PublicSubnetCIDR: 10.10.20.0/24

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-zuram.s3.us-east-2.amazonaws.com/infrastructure/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-zuram.s3.us-east-2.amazonaws.com/infrastructure/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        ClusterSize: 1
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup

  FrontedService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-zuram.s3.us-east-2.amazonaws.com/services/frontend/service.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Cluster: !GetAtt ECSCluster.Outputs.Cluster
        ECSTaskExecutionRole: !GetAtt ECSCluster.Outputs.ECSTaskExecutionRole
